import Head from 'next/head';
import { NextPageContext } from 'next';
import React, { FC } from 'react';

const user: FC<{ collection: string }> = ({ collection }) => {
  return (
    <div className="">
      <Head>
        <title>{collection}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{collection}</main>
    </div>
  );
};

export const getServerSideProps = async (
  context: NextPageContext
): Promise<{
  props: {
    collection: string;
  };
}> => {
  return {
    props: {
      // @ts-ignore
      collection: context.query.collection.toString(),
    },
  };
};

export default user;
