import Head from 'next/head';
import { NextPageContext } from 'next';
import React from 'react';
import { useGetUserInfoQuery } from '../../src/graphql/user.graphql';

const user = ({ username }: { username: string }) => {
  const { data, loading, error } = useGetUserInfoQuery({
    variables: { user: username },
  });

  if (error) return <div>error</div>;
  if (loading) return <div>loading</div>;
  if (data?.getUserInfo === null) return <div>user does not exist</div>;

  return (
    <div className="">
      <Head>
        <title>{username}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data?.getUserInfo?.first_name} {data?.getUserInfo?.last_name}
      </div>
      <div>{data?.getUserInfo?.username}</div>
    </div>
  );
};

export const getServerSideProps = async (context: NextPageContext) => {
  return {
    props: {
      // @ts-ignore
      username: context.query.username.toString(),
    },
  };
};

export default user;
