import 'tailwindcss/tailwind.css';
import Head from 'next/head';
import React from 'react';
import dynamic from 'next/dynamic';

const MapWithNoSSR = dynamic(() => import('../src/components/map'), {
  ssr: false,
});

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        hiStories
        <MapWithNoSSR />
      </main>
    </div>
  );
}
