import Head from 'next/head';
import { NextPageContext } from 'next';
import React from 'react';

const user = ({ collection }: { collection: string }) => {
  return (
    <div className="">
      <Head>
        <title>{collection}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{collection}</main>
    </div>
  );
};

export const getServerSideProps = async (context: NextPageContext) => {
  return {
    props: {
      // @ts-ignore
      collection: context.query.collection.toString(),
    },
  };
};

export default user;
