import Head from 'next/head';
import { NextPageContext } from 'next';
import React from 'react';

const user = ({ post }: { post: string }): JSX.Element => {
  return (
    <div className="">
      <Head>
        <title>{post}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{post}</main>
    </div>
  );
};

export const getServerSideProps = async (
  context: NextPageContext
): Promise<{
  props: {
    post: string;
  };
}> => {
  return {
    props: {
      // @ts-ignore
      post: context.query.post.toString(),
    },
  };
};

export default user;
